### PR TITLE
magento/magento2-login-as-customer#150: Opt-in/out V3.

### PR DESCRIPTION
**Pull request by engcom-Foxtrot**
### Related Pull Requests
https://github.com/magento/partners-magento2ee/pull/304

### Fixed Issues (if relevant)

1. Fixes https://github.com/magento/magento2/issues/29113: Customers should be able to enable/disable Admin "remote shopping assistance". 
2. Fixes https://github.com/magento/magento2/issues/29114: Admin is able to change "Allow remote shopping assistance" option without access to "Change customer opt-in preference"

### Manual testing scenarios (*)

1. See https://github.com/magento/magento2/issues/29113: Customers should be able to enable/disable Admin "remote shopping assistance". 
2. See https://github.com/magento/magento2/issues/29114: Admin is able to change "Allow remote shopping assistance" option without access to "Change customer opt-in preference"

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by engcom-Foxtrot** [comment]
@magento run all tests

**Comment by naydav** [comment]
@magento run all tests

**Comment by engcom-Foxtrot** [comment]
@magento run all tests

**Comment by naydav** [comment]
@magento run all tests

**Comment by naydav** [comment]
@magento run all tests

**Comment by engcom-Foxtrot** [comment]
@magento run all tests

**Comment by engcom-Foxtrot** [comment]
@magento run all tests

**Comment by engcom-Foxtrot** [comment]
@magento run all tests

**Comment by engcom-Delta** [comment]
**Results** of testing `Opt-in permission state can be viewed and modified using Customer API` from https://github.com/magento/magento2/issues/29113 :

- Every response for GET, PUT or POST requests does not contain `assistance_allowed` attribute in 'extension_attributes' section
image
 

- Not obvious values of `assistance_allowed` attribute to enable/disable Opt-in
- - "assistance_allowed": "1" - disable Opt-in
- - "assistance_allowed": "2" - enable Opt-in


- Opt-in permission state can be modified using Customer API
- - `PUT /V1/customers/:customerId`
- - `PUT /V1/customers/me`
- - `POST /V1/customers`

**Comment by engcom-Foxtrot** [comment]
@magento run all tests

**Comment by engcom-Foxtrot** [comment]
@magento run all tests

**Comment by engcom-Delta** [comment]
:heavy_check_mark: QA passed
Was checked cases created customer on front/backend with/without Opt-in/out, edit customer Opt-in/out checkbox on front/backend,disable/enable Opt-in/out using ACL permissions

**Comment by engcom-Foxtrot** [comment]
Merged in https://github.com/magento/magento2ce/pull/5994

**Pull request closed without merging**
