### PR TITLE
magento/magento2-login-as-customer#150: Opt-in/out.

### PR DESCRIPTION
**Pull request by engcom-Foxtrot**
### Fixed Issues (if relevant)

1. Fixes magento/magento2-login-as-customer#150: Opt-in/out.
2. Fixes magento/magento2-login-as-customer#152: Admin is able to change "Allow remote shopping assistance" option without access to "Change customer opt-in preference"

### Manual testing scenarios (*)

1. See magento/magento2-login-as-customer#150.
1. See magento/magento2-login-as-customer#152.

### Questions or comments

ACL restrictions for "Allow remote shopping assistance" checkbox not yet implemented.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by engcom-Delta** [comment]
:heavy_check_mark: QA passed
Was checked cases:

- https://studio.cucumber.io/projects/163172/test-plan/folders/1204738/scenarios/4682808
- https://studio.cucumber.io/projects/163172/test-plan/folders/1204738/scenarios/4682862
- https://studio.cucumber.io/projects/163172/test-plan/folders/1204738/scenarios/4683024
- https://studio.cucumber.io/projects/163172/test-plan/folders/1204738/scenarios/4683080
- https://studio.cucumber.io/projects/163172/test-plan/folders/1204738/scenarios/4696600

**Comment by engcom-Foxtrot** [comment]
@magento run all tests

**Comment by engcom-Foxtrot** [comment]
@magento run all tests

**Comment by engcom-Foxtrot** [comment]
@magento run all tests

**Comment by engcom-Delta** [comment]
:heavy_check_mark: Issue https://github.com/magento/magento2-login-as-customer/issues/152 is fixed by PR
**Result:**

- Admin user with no access to "Allow remote shopping assistance" option on customer edit page

image

- Admin user with no access to "Allow remote shopping assistance" option on create new customer page

image

**Notice.** There is case when admin user could disable "Allow remote shopping assistance" from customer "My Account" if this option was enabled. This behavior should be approved or defined as bug
**Manual testing scenario:**

- Create user with enabled "Allow remote shopping assistance" option
- Create admin with role "Custom" that has no access to "Allow remote shopping assistance" option
- Log in admin panel as admin with role "Custom"
- Go to Customers->All Customers
- Click Edit action for customer with enabled "Allow remote shopping assistance" option
- Click on Account Information
- Uncheck "Allow remote shopping assistance"
- Click Save

**Result:**

- Account information is successfully saved
- Allow remote shopping assistance" option is disabled
- Admin user is logged in as customer

**Comment by engcom-Foxtrot** [comment]
@magento run all tests

**Comment by engcom-Foxtrot** [comment]
@magento run all tests

**Comment by engcom-Foxtrot** [comment]
@magento run all tests

**Comment by engcom-Foxtrot** [comment]
@magento run all tests

**Comment by engcom-Foxtrot** [comment]
@magento run all tests

**Comment by engcom-Foxtrot** [comment]
@magento run all tests

**Comment by engcom-Foxtrot** [comment]
@magento run all tests

**Comment by engcom-Foxtrot** [comment]
@magento run all tests

**Comment by engcom-Foxtrot** [comment]
@magento run all tests

**Comment by naydav** [comment]
Closed in favor https://github.com/magento/magento2-login-as-customer/pull/160

**Pull request closed without merging**
