### PR TITLE
MFTF tests - green.

### PR DESCRIPTION
**Pull request by engcom-Foxtrot**
Copy of https://github.com/magento/magento2-login-as-customer/pull/93 but with failing tests skipped.

### CODE REVIEW

**Comment by engcom-Foxtrot** [comment]
@magento run all tests

**Comment by engcom-Foxtrot** [comment]
@magento run all tests

**Comment by engcom-Foxtrot** [comment]
@magento run all tests

**Comment by engcom-Foxtrot** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
Hi @naydav, this PR almost ready to merge.

**Comment by engcom-Foxtrot** [comment]
@magento run all tests

**Comment by naydav** [comment]
@magento run all tests

**Comment by engcom-Foxtrot** [comment]
@magento run all tests

**Pull request merged**
